
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
env:
  APP_NAME: sabyasachi-java-demo

jobs:
  pre-build:
    name: Pre Build
    runs-on: ubuntu-latest
    env:
      STAGE_NAME: before_package
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn compile
        mvn test
        echo "App Name: APP_NAME"
        echo "Stage Name: $STAGE_NAME"
        
  build:
    name: build
    runs-on: ubuntu-latest
    needs: pre-build
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn package
        echo "App Name: APP_NAME"
        echo "Stage Name: $STAGE_NAME"
        
    - uses: actions/upload-artifact@v4
      with:
        name: boardgame
        path: target/*jar
        
    
